# Docker Compose for Mentoring W8
services:

  db_mentoring_w8:
    image: postgres:16
    container_name: db_mentoring_w8
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pacmann


networks:
  pacmann:
    driver: bridge

volumes:
  postgres_data:
    driver: local
